#!/usr/bin/env python3
"""Generate the "File map (for remote fetchers)" section for a venture README.

Walks the venture folder and groups files into buckets:
  - Tokens & docs:    every file at the venture root
  - Brand assets:     `assets/` (flat)
  - Reference uploads:`uploads/` (flat)
  - Preview cards:    `preview/` (flat)
  - UI kit:           one bucket per `ui_kits/<kit>/` (recursive)
  - Custom:           any other subfolder under the venture (recursive)

Unknown subfolders auto-appear as their own bucket, so a venture with
unique structure (motion specs, brand-book PDFs, Figma exports, etc.)
gets correctly mapped without changes to this script.

Usage:
    tools/generate-file-map.py design-systems/pps
        Print the section to stdout.

    tools/generate-file-map.py design-systems/pps --write
        Replace the section between FILE_MAP_START / FILE_MAP_END markers
        in <venture>/README.md.
"""
from __future__ import annotations

import argparse
import sys
import urllib.parse
from pathlib import Path

BASE_URL = "https://gsc-ventures.netlify.app/"
START = "<!-- FILE_MAP_START -->"
END = "<!-- FILE_MAP_END -->"

KNOWN_FLAT = [
    ("assets",  "Brand assets (`assets/`)"),
    ("uploads", "Reference uploads (`uploads/`)"),
    ("preview", "Preview cards (`preview/`)"),
]


def url_for(repo_relpath: str) -> str:
    return BASE_URL + urllib.parse.quote(repo_relpath)


def flat_files(folder: Path) -> list[Path]:
    if not folder.is_dir():
        return []
    return sorted(
        p for p in folder.iterdir()
        if p.is_file() and not p.name.startswith(".")
    )


def recursive_files(folder: Path) -> list[Path]:
    if not folder.is_dir():
        return []
    out = []
    for p in sorted(folder.rglob("*")):
        if any(part.startswith(".") for part in p.parts):
            continue
        if p.is_file():
            out.append(p)
    return out


def render_bucket(heading: str, files: list[Path], repo_root: Path,
                  display_root: Path | None = None) -> str:
    lines = [f"### {heading}"]
    for p in files:
        rel = p.relative_to(repo_root).as_posix()
        if display_root is not None:
            disp = p.relative_to(display_root).as_posix()
        else:
            disp = p.name
        lines.append(f"- `{disp}` — {url_for(rel)}")
    return "\n".join(lines)


def build_section(venture: Path, repo_root: Path) -> str:
    sections: list[str] = []
    seen_dirs: set[str] = set()

    root_files = flat_files(venture)
    if root_files:
        sections.append(render_bucket("Tokens & docs", root_files, repo_root))

    for sub, heading in KNOWN_FLAT:
        files = flat_files(venture / sub)
        if files:
            seen_dirs.add(sub)
            sections.append(render_bucket(heading, files, repo_root))

    ui_kits = venture / "ui_kits"
    if ui_kits.is_dir():
        seen_dirs.add("ui_kits")
        for kit_dir in sorted(
            p for p in ui_kits.iterdir()
            if p.is_dir() and not p.name.startswith(".")
        ):
            files = recursive_files(kit_dir)
            if files:
                heading = f"UI kit (`ui_kits/{kit_dir.name}/`)"
                sections.append(render_bucket(heading, files, repo_root, kit_dir))

    for sub in sorted(p for p in venture.iterdir()
                      if p.is_dir() and not p.name.startswith(".")):
        if sub.name in seen_dirs:
            continue
        files = recursive_files(sub)
        if files:
            heading = f"Custom (`{sub.name}/`)"
            sections.append(render_bucket(heading, files, repo_root, sub))

    intro = (
        "## File map (for remote fetchers)\n\n"
        "Every file in this folder, by full Netlify URL. A remote Claude that has "
        "fetched this README now has every URL it needs in context — `web_fetch` "
        "will accept any of them. Generated by `tools/generate-file-map.py`; do "
        "not hand-edit between the markers below.\n"
    )
    body = "\n\n".join(sections)
    return f"{START}\n{intro}\n{body}\n{END}"


def write_section(readme: Path, block: str) -> None:
    if not readme.is_file():
        sys.exit(f"README not found: {readme}")
    text = readme.read_text()
    if START in text and END in text:
        before, _, rest = text.partition(START)
        _, _, after = rest.partition(END)
        readme.write_text(before + block + after)
        print(f"Updated {readme}")
        return
    sys.exit(
        f"Markers not found in {readme}. Insert this block, then re-run "
        f"with --write:\n\n{block}\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("venture", help="Path to venture folder, e.g. design-systems/pps")
    ap.add_argument("--write", action="store_true",
                    help="Replace the marked section in <venture>/README.md")
    args = ap.parse_args()

    venture = Path(args.venture).resolve()
    if not venture.is_dir():
        sys.exit(f"Not a directory: {venture}")

    repo_root = Path(__file__).resolve().parent.parent
    try:
        venture.relative_to(repo_root)
    except ValueError:
        sys.exit(f"{venture} is not inside repo root {repo_root}")

    block = build_section(venture, repo_root)

    if args.write:
        write_section(venture / "README.md", block)
    else:
        print(block)


if __name__ == "__main__":
    main()
